version: '3.8'

services:
  qltc-client:
    image: ${DOCKER_USERNAME}/qltc-client:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - qltc-network

  qltc-server:
    image: ${DOCKER_USERNAME}/qltc-server:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_USER_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 1m
      timeout: 10s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - qltc-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - qltc-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

volumes:
  mysql-data:
    driver: local

networks:
  qltc-network:
    driver: bridge 