version: '3.8'

services:
  client:
    image: ${DOCKER_USERNAME}/qltc-client:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - qltc-network

  server:
    image: ${DOCKER_USERNAME}/qltc-server:${IMAGE_TAG:-latest}
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    networks:
      - qltc-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - qltc-network

volumes:
  mysql_data:

networks:
  qltc-network:
    driver: bridge 