name: Development Docker CI

on:
  push:
    branches: [ develop, feature/*, dev, main ]
  pull_request:
    branches: [ develop, main ]
  # Allow manual trigger
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_TAG: dev-${{ github.sha }}

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Create the environment files from secrets
      - name: Create environment files
        run: |
          # Create client .env.development
          echo "${{ secrets.CLIENT_ENV_DEVELOPMENT }}" > ./client/.env.development
          
          # Create server .env.development
          echo "${{ secrets.SERVER_ENV_DEVELOPMENT }}" > ./server/.env.development

      - name: Build and push client dev image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/qltc-client-dev:latest,${{ secrets.DOCKER_USERNAME }}/qltc-client-dev:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/qltc-client-dev:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/qltc-client-dev:buildcache,mode=max

      - name: Build and push server dev image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/qltc-server-dev:latest,${{ secrets.DOCKER_USERNAME }}/qltc-server-dev:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/qltc-server-dev:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/qltc-server-dev:buildcache,mode=max

      - name: Create .env file for deployment
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env.dev
          echo "IMAGE_TAG=dev-${{ github.sha }}" >> .env.dev

      - name: Upload .env as artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-dev-file
          path: .env.dev 
